
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sebastian
 */
public class Ventana extends javax.swing.JFrame {
    Validacion val = new Validacion();
    Conversion con = new Conversion();
    private int dec;
    private int bin;
    private int oct;
    private String hex;
    private String decimalResultante;
    private String binarioResultante;
    private String octalResultante;
    private String hexadecimalResultante;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Txtcampo = new javax.swing.JTextField();
        BtnDecaBin = new javax.swing.JButton();
        BtnDecaOct = new javax.swing.JButton();
        BtnDecaHex = new javax.swing.JButton();
        BntBinaDec = new javax.swing.JButton();
        BtnBinaOct = new javax.swing.JButton();
        BtnBinaHex = new javax.swing.JButton();
        BtnOctaDec = new javax.swing.JButton();
        BtnOctaBin = new javax.swing.JButton();
        BtnOctaHex = new javax.swing.JButton();
        BtnHexaDec = new javax.swing.JButton();
        BtnHexaBin = new javax.swing.JButton();
        BtnHexaOct = new javax.swing.JButton();
        TxtResult = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnLimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversion de bases");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(53, 114, 108));

        BtnDecaBin.setBackground(new java.awt.Color(247, 240, 82));
        BtnDecaBin.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 14)); // NOI18N
        BtnDecaBin.setText("Decimal a binario");
        BtnDecaBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDecaBinActionPerformed(evt);
            }
        });

        BtnDecaOct.setBackground(new java.awt.Color(247, 240, 82));
        BtnDecaOct.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 14)); // NOI18N
        BtnDecaOct.setText("Decimal a octal");
        BtnDecaOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDecaOctActionPerformed(evt);
            }
        });

        BtnDecaHex.setBackground(new java.awt.Color(247, 240, 82));
        BtnDecaHex.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 14)); // NOI18N
        BtnDecaHex.setText("Decimal a hexadecimal");
        BtnDecaHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDecaHexActionPerformed(evt);
            }
        });

        BntBinaDec.setBackground(new java.awt.Color(242, 129, 35));
        BntBinaDec.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 14)); // NOI18N
        BntBinaDec.setText("Binario a decimal");
        BntBinaDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntBinaDecActionPerformed(evt);
            }
        });

        BtnBinaOct.setBackground(new java.awt.Color(242, 129, 35));
        BtnBinaOct.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 14)); // NOI18N
        BtnBinaOct.setText("Binario a octal");
        BtnBinaOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBinaOctActionPerformed(evt);
            }
        });

        BtnBinaHex.setBackground(new java.awt.Color(242, 129, 35));
        BtnBinaHex.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 14)); // NOI18N
        BtnBinaHex.setText("Binaro a hexadecimal");
        BtnBinaHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBinaHexActionPerformed(evt);
            }
        });

        BtnOctaDec.setBackground(new java.awt.Color(211, 78, 36));
        BtnOctaDec.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 14)); // NOI18N
        BtnOctaDec.setText("Octal a decimal");
        BtnOctaDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOctaDecActionPerformed(evt);
            }
        });

        BtnOctaBin.setBackground(new java.awt.Color(211, 78, 36));
        BtnOctaBin.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 14)); // NOI18N
        BtnOctaBin.setText("Octal a binario");
        BtnOctaBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOctaBinActionPerformed(evt);
            }
        });

        BtnOctaHex.setBackground(new java.awt.Color(211, 78, 36));
        BtnOctaHex.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 14)); // NOI18N
        BtnOctaHex.setText("Octal a hexadecimal");
        BtnOctaHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOctaHexActionPerformed(evt);
            }
        });

        BtnHexaDec.setBackground(new java.awt.Color(86, 63, 27));
        BtnHexaDec.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 14)); // NOI18N
        BtnHexaDec.setText("Hexadecimal a decimal");
        BtnHexaDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHexaDecActionPerformed(evt);
            }
        });

        BtnHexaBin.setBackground(new java.awt.Color(86, 63, 27));
        BtnHexaBin.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 14)); // NOI18N
        BtnHexaBin.setText("Hexadecimal a binario");
        BtnHexaBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHexaBinActionPerformed(evt);
            }
        });

        BtnHexaOct.setBackground(new java.awt.Color(86, 63, 27));
        BtnHexaOct.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 14)); // NOI18N
        BtnHexaOct.setText("Hexadeciaml a octal");
        BtnHexaOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHexaOctActionPerformed(evt);
            }
        });

        TxtResult.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Escriba el número que desea convertir: ");

        jLabel2.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Resultado conversión:");

        BtnLimpiar.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 14)); // NOI18N
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>Integrantes:<p><p> Sebastian Morales Tarapues   20182020039<p><p> Brayan Alejandro Riveros Rodríguez   20201020084<p><p> Guillermo Steven Cuesta Castellanos   20192020102<p><p> Jersson Javier Ortegate Banderas   20201020139<hmtl>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Txtcampo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BtnDecaBin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BtnDecaOct, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BtnDecaHex))
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BntBinaDec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnBinaOct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnBinaHex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(34, 34, 34)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(BtnOctaDec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BtnOctaHex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(BtnOctaBin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BtnHexaDec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnHexaBin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnHexaOct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(TxtResult, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Txtcampo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnDecaBin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BntBinaDec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnOctaDec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnHexaDec, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnHexaBin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOctaBin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBinaOct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDecaOct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDecaHex, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBinaHex, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOctaHex, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHexaOct, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        TxtResult.setText("");
        Txtcampo.setText("");
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnHexaOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHexaOctActionPerformed
        try {
            hex = Txtcampo.getText().toUpperCase();
            if (!val.validarHexadecimal(hex)) {
                JOptionPane.showMessageDialog(null,"El valor que desea convertir no es un hexadecimal"
                    +"\n"+"Recuerda los hexadecimales usan 16 símbolos:"
                    +"\n"+" (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)"+"\n"+"(A ,B ,C ,D ,E ,F)"
                    ,"Validación",JOptionPane.ERROR_MESSAGE);
            }else{
                dec = con.hexadecimalADecimal(hex);
                octalResultante = con.decimalAOctal(dec);
                TxtResult.setText(octalResultante);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"El valor que desea convertir no es un hexadecimal"
                +"\n"+"Recuerda los hexadecimales usan 16 símbolos:"
                +"\n"+" (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)"+"\n"+"(A ,B ,C ,D ,E ,F)"
                ,"Validación",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnHexaOctActionPerformed

    private void BtnHexaBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHexaBinActionPerformed
        try {
            hex = Txtcampo.getText().toUpperCase();
            if (!val.validarHexadecimal(hex)) {
                JOptionPane.showMessageDialog(null,"El valor que desea convertir no es un hexadecimal"
                    +"\n"+"Recuerda los hexadecimales usan 16 símbolos:"
                    +"\n"+" (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)"+"\n"+"(A ,B ,C ,D ,E ,F)"
                    ,"Validación",JOptionPane.ERROR_MESSAGE);
            }else{
                dec = con.hexadecimalADecimal(hex);
                binarioResultante = con.decimalABinario(dec);
                TxtResult.setText(binarioResultante);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"El valor que desea convertir no es un hexadecimal"
                +"\n"+"Recuerda los hexadecimales usan 16 símbolos:"
                +"\n"+" (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)"+"\n"+"(A ,B ,C ,D ,E ,F)"
                ,"Validación",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnHexaBinActionPerformed

    private void BtnHexaDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHexaDecActionPerformed
        try {
            hex = Txtcampo.getText().toUpperCase();
            if (!val.validarHexadecimal(hex)) {
                JOptionPane.showMessageDialog(null,"El valor que desea convertir no es un hexadecimal"
                    +"\n"+"Recuerda los hexadecimales usan 16 símbolos:"
                    +"\n"+" (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)"+"\n"+"(A ,B ,C ,D ,E ,F)"
                    ,"Validación",JOptionPane.ERROR_MESSAGE);
            }else{
                dec = con.hexadecimalADecimal(hex);
                decimalResultante = String.valueOf(dec);
                TxtResult.setText(decimalResultante);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"El valor que desea convertir no es un hexadecimal"
                +"\n"+"Recuerda los hexadecimales usan 16 símbolos:"
                +"\n"+" (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)"+"\n"+"(A ,B ,C ,D ,E ,F)"
                ,"Validación",JOptionPane.ERROR_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnHexaDecActionPerformed

    private void BtnOctaHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOctaHexActionPerformed
        try {
            oct = Integer.parseInt(Txtcampo.getText());
            if (!val.validarOctal(oct)) {
                JOptionPane.showMessageDialog(null,"El valor que desea convertir no es un octal"
                    +"\n"+"Recuerda los octales usan 8 dígitos:"+"\n"+" (0, 1, 2, 3, 4, 5, 6, 7)"
                    ,"Validación",JOptionPane.ERROR_MESSAGE);
            }else{
                dec = con.octalADecimal(oct);
                hexadecimalResultante = con.decimalAHexadecimal(dec);
                TxtResult.setText(hexadecimalResultante);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"El valor que desea ingresar presenta caracteres"
                +"\n"+"Recuerda los octales usan 8 dígitos (0, 1, 2, 3, 4, 5, 6, 7)"
                ,"Validación",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnOctaHexActionPerformed

    private void BtnOctaBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOctaBinActionPerformed
        try {
            oct = Integer.parseInt(Txtcampo.getText());
            if (!val.validarOctal(oct)) {
                JOptionPane.showMessageDialog(null,"El valor que desea convertir no es un octal"
                    +"\n"+"Recuerda los octales usan 8 dígitos:"+"\n"+" (0, 1, 2, 3, 4, 5, 6, 7)"
                    ,"Validación",JOptionPane.ERROR_MESSAGE);
            }else{
                dec = con.octalADecimal(oct);
                binarioResultante = con.decimalABinario(dec);
                TxtResult.setText(binarioResultante);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"El valor que desea ingresar presenta caracteres"
                +"\n"+"Recuerda los octales usan 8 dígitos (0, 1, 2, 3, 4, 5, 6, 7)"
                ,"Validación",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnOctaBinActionPerformed

    private void BtnOctaDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOctaDecActionPerformed
        try {
            oct = Integer.parseInt(Txtcampo.getText());
            if (!val.validarOctal(oct)) {
                JOptionPane.showMessageDialog(null,"El valor que desea convertir no es un octal"
                    +"\n"+"Recuerda los octales usan 8 dígitos:"+"\n"+" (0, 1, 2, 3, 4, 5, 6, 7)"
                    ,"Validación",JOptionPane.ERROR_MESSAGE);
            }else{
                dec = con.octalADecimal(oct);
                octalResultante = String.valueOf(dec);
                TxtResult.setText(octalResultante);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"El valor que desea ingresar presenta caracteres"
                +"\n"+"Recuerda los octales usan 8 dígitos (0, 1, 2, 3, 4, 5, 6, 7)"
                ,"Validación",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnOctaDecActionPerformed

    private void BtnBinaHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBinaHexActionPerformed
        try {
            bin = Integer.parseInt(Txtcampo.getText());
            if (!val.validarBinario(bin)) {
                JOptionPane.showMessageDialog(null,"El valor que desea convertir no es un binario"
                    +"\n"+"Recuerda los binarios son escritos con 1 y 0"
                    ,"Validación",JOptionPane.ERROR_MESSAGE);
            }else{
                dec = con.binarioADecimal(bin);
                hexadecimalResultante = con.decimalAHexadecimal(dec);
                TxtResult.setText(hexadecimalResultante);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"El valor que desea ingresar presenta caracteres"
                +"\n"+"Recuerda los binarios son escritos con 1 y 0"
                ,"Validación",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnBinaHexActionPerformed

    private void BtnBinaOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBinaOctActionPerformed
        try {
            bin = Integer.parseInt(Txtcampo.getText());
            if (!val.validarBinario(bin)) {
                JOptionPane.showMessageDialog(null,"El valor que desea convertir no es un binario"
                    +"\n"+"Recuerda los binarios son escritos con 1 y 0"
                    ,"Validación",JOptionPane.ERROR_MESSAGE);
            }else{
                dec = con.binarioADecimal(bin);
                octalResultante = con.decimalAOctal(dec);
                TxtResult.setText(octalResultante);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"El valor que desea ingresar presenta caracteres"
                +"\n"+"Recuerda los binarios son escritos con 1 y 0"
                ,"Validación",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnBinaOctActionPerformed

    private void BntBinaDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntBinaDecActionPerformed
        try {
            bin = Integer.parseInt(Txtcampo.getText());
            if (!val.validarBinario(bin)) {
                JOptionPane.showMessageDialog(null,"El valor que desea convertir no es un binario"
                    +"\n"+"Recuerda los binarios son escritos con 1 y 0"
                    ,"Validación",JOptionPane.ERROR_MESSAGE);
            }else{
                decimalResultante = String.valueOf(con.binarioADecimal(bin));
                TxtResult.setText(decimalResultante);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"El valor que desea ingresar presenta caracteres"
                +"\n"+"Recuerda los binarios son escritos con 1 y 0"
                ,"Validación",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BntBinaDecActionPerformed

    private void BtnDecaHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDecaHexActionPerformed
        try {
            dec = Integer.parseInt(Txtcampo.getText());
            hexadecimalResultante = con.decimalAHexadecimal(dec);
            TxtResult.setText(hexadecimalResultante);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"El valor que desea convertir no es decimal"
                ,"Validación",JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDecaHexActionPerformed

    private void BtnDecaOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDecaOctActionPerformed
        try {
            dec = Integer.parseInt(Txtcampo.getText());
            octalResultante = con.decimalAOctal(dec);
            TxtResult.setText(octalResultante);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"El valor que desea convertir no es decimal"
                ,"Validación",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnDecaOctActionPerformed

    private void BtnDecaBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDecaBinActionPerformed
        try {
            dec = Integer.parseInt(Txtcampo.getText());
            binarioResultante = con.decimalABinario(dec);
            TxtResult.setText(binarioResultante);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"El valor que desea convertir no es decimal"
                ,"Validación",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BtnDecaBinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntBinaDec;
    private javax.swing.JButton BtnBinaHex;
    private javax.swing.JButton BtnBinaOct;
    private javax.swing.JButton BtnDecaBin;
    private javax.swing.JButton BtnDecaHex;
    private javax.swing.JButton BtnDecaOct;
    private javax.swing.JButton BtnHexaBin;
    private javax.swing.JButton BtnHexaDec;
    private javax.swing.JButton BtnHexaOct;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnOctaBin;
    private javax.swing.JButton BtnOctaDec;
    private javax.swing.JButton BtnOctaHex;
    private javax.swing.JTextField TxtResult;
    private javax.swing.JTextField Txtcampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
